import os
import re

from dotenv import load_dotenv

TECHNOCORE_API = "https://technocore.chat"
ROOMS_LIMIT = 5
MESSAGES_LIMIT = 10
MAILBOX_MESSAGES_LIMIT = 20
WATCH_FETCH_LIMIT = 200
WATCH_POLL_INTERVAL = 30
MAX_WATCHES_PER_USER = 5
REQUEST_TIMEOUT = 10
TELEGRAM_TEXT_LIMIT = 3900
DATABASE_PATH = "technocore.db"

ROOM_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{0,47}$")
MULTICODEC_ED25519 = b"\xed\x01"
INVISIBLE_CATEGORIES = ("Cc", "Cf", "Cs", "Co", "Zl", "Zp")
MAX_MESSAGE_CHARS = 4096
MAX_NOTE_CHARS = 8192

E2E_INFO = b"technocore-e2e-v1"
E2E_INVITE_PREFIX = "e2e1"
E2E_ROOM_PREFIX = "p-"
E2E_INBOX_LIMIT = 200
E2E_ROOM_MESSAGES_LIMIT = 50
MAX_E2E_PLAINTEXT_CHARS = 2000

SCRYPT_N = 2**15
SCRYPT_R = 8
SCRYPT_P = 1
SCRYPT_KEY_LENGTH = 32
SALT_SIZE = 16
AES_NONCE_SIZE = 12
MIN_PASSWORD_LENGTH = 10
MAX_PASSWORD_ATTEMPTS = 3

BACKUP_FORMAT = "technocore-gateway-backup"
BACKUP_VERSION = 2
MAX_BACKUP_SIZE = 250_000

load_dotenv()
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
